### ISSUE TITLE
Image is flipped (mirrored)

### ISSUE THREAD

**Issue by matthijsvdr** [flywheel-io/cornerstone-nifti-image-loader#4]
Hi,
We are using your nifti loader to create an overlay (layer) on top of dicom images loaded.
But the dicom and nifti are mirored of eacher other.
With dicom slices the head is turned to the right but when we then overlay the nifti head is pointing to the left.
Do you have any idea what could be causing this? 

Greetings,
Matthijs

// edit

When using a view like itk-snap to load the same nifti file it matches the cornerstone load of dicom slices, so somewhere the image of the nifti get flipped when using this loader.

**Comment by gwq123456** [comment]
How is this problem solved?I'm confused, too

**Comment by matthijsvdr** [comment]
> @matthijsvdr Sorry to ping you! Could you briefly discuss why you closed the issue? I am facing the same problem.

Sorry but this was long ago I don't remember.

**Comment by ramonemiliani93** [comment]
If anyone is facing the issue check [this](https://github.com/cornerstonejs/cornerstone-nifti-image-loader/issues/17#issuecomment-1174413499).

**Comment by ITCore99** [comment]
I am facing the same problem. How is this problem solved? I'm confused, too
